/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;
import Controller.ProdutoController;
import Model.Produto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Maicon Virgens
 */
public class TelaProduto extends javax.swing.JInternalFrame {
    private  ProdutoController produtoController;

    /**
     * Creates new form Produto
     */
    public TelaProduto() {
        initComponents();
        CarregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProdutoCriar = new javax.swing.JButton();
        btnProdutoAtualizar = new javax.swing.JButton();
        btnProdutoDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtProdutoId = new javax.swing.JTextField();
        txtProdutoNome = new javax.swing.JTextField();
        txtProdutoQuant = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProdutoPreco = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(599, 455));

        btnProdutoCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/create (1).png"))); // NOI18N
        btnProdutoCriar.setToolTipText("Adicionar");
        btnProdutoCriar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProdutoCriar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnProdutoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoCriarActionPerformed(evt);
            }
        });

        btnProdutoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/update.png"))); // NOI18N
        btnProdutoAtualizar.setToolTipText("");
        btnProdutoAtualizar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnProdutoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoAtualizarActionPerformed(evt);
            }
        });

        btnProdutoDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/delete.png"))); // NOI18N
        btnProdutoDelete.setToolTipText("");
        btnProdutoDelete.setPreferredSize(new java.awt.Dimension(80, 80));
        btnProdutoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoDeleteActionPerformed(evt);
            }
        });

        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Quantidade", "Preço"
            }
        ));
        tbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduto);

        jLabel1.setText("Id");

        jLabel2.setText("Nome");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Preço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel4))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProdutoId)
                                    .addComponent(txtProdutoNome)
                                    .addComponent(txtProdutoQuant)
                                    .addComponent(txtProdutoPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnProdutoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(btnProdutoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProdutoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdutoQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProdutoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdutoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarregarTabela(){
         List<Produto> produtos = new ArrayList<>();
        
        produtoController = new ProdutoController();
        
        
        DefaultTableModel model =(DefaultTableModel) tbProduto.getModel();
        model.setNumRows(0);
        
        try {
             
             produtos = produtoController.listarProdutos();
             
             produtos.forEach(item -> {
                //System.out.println(item.getNome());       
                model.addRow(new Object[] 
                    { 
                       //retorna os dados da tabela do BD, cada campo e um coluna.
                      
                        item.getId_produto(),
                        item.getNome(),
                        item.getQuantidade(),
                        item.getPreco()
                     
                    });  
            });
        } catch (Exception e) {
            
        }
        
    }

    
    private void btnProdutoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoCriarActionPerformed
        //Produto produto = new Produto();
        
        int result = 0;
        
        
        if(txtProdutoNome.getText().isEmpty() || txtProdutoQuant.getText().isEmpty() || txtProdutoPreco.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }else{
            String textoQuant = txtProdutoQuant.getText();
            String textoPreco = txtProdutoPreco.getText();
            
             try {
                    produtoController = new ProdutoController();
                    
                    Produto produto = new Produto();
                    
   
                    int quantP = Integer.parseInt(textoQuant);
                    double precoP = Double.parseDouble(textoPreco);
                    
                    produto.setNome(txtProdutoNome.getText());
                    produto.setQuantidade(quantP);
                    produto.setPreco(precoP);
                    
                    result = produtoController.adicionarProduto(produto);
                    
                    if(result > 0){
                        JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso");
                        txtProdutoId.setText(null);
                        txtProdutoNome.setText(null);
                        txtProdutoPreco.setText(null);
                        txtProdutoQuant.setText(null);
                        CarregarTabela();
                         
                    }
                  
                    
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Preencha com um número.");
                   
                }
            
           // result = produtoController.adicionarProduto(txtProdutoNome.getText(), txtProdutoQuant.getText(), txtProdutoPreco.getText());   
        }
    }//GEN-LAST:event_btnProdutoCriarActionPerformed

    private void btnProdutoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoAtualizarActionPerformed
         //Produto produto = new Produto();
         
        int result = 0;

        if(txtProdutoNome.getText().isEmpty() || txtProdutoQuant.getText().isEmpty() || txtProdutoPreco.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }else{
            String textoIdInt = txtProdutoId.getText();
            String textoQuantInt = txtProdutoQuant.getText();
            String textoDouble = txtProdutoPreco.getText();
     
            try {
                   produtoController = new ProdutoController();
                   Produto produto = new Produto();
                   
                   
                   int idInt = Integer.parseInt(textoIdInt);
                   int quantidade = Integer.parseInt(textoQuantInt);
                   double preco = Double.parseDouble(textoDouble);
                   
                   produto.setId_produto(idInt);
                   produto.setNome(txtProdutoNome.getText());
                   produto.setQuantidade(quantidade);
                   produto.setPreco(preco);
                   
                   
                   result = produtoController.alterarProduto(produto);

                   if(result > 0){
                       JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso");
                       txtProdutoId.setText(null);
                       txtProdutoNome.setText(null);
                       txtProdutoPreco.setText(null);
                       txtProdutoQuant.setText(null);
                       CarregarTabela();     
                   }          
               } catch (NumberFormatException ex) {
                   JOptionPane.showMessageDialog(null, "Preencha com um número.");    
               } 
        }  
    }//GEN-LAST:event_btnProdutoAtualizarActionPerformed

    private void btnProdutoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoDeleteActionPerformed
        int linhaSelecionada = tbProduto.getSelectedRow();

        if (linhaSelecionada != -1) {
            TableModel dadosTabela = tbProduto.getModel();

            String id_produto = dadosTabela.getValueAt(linhaSelecionada, 0).toString();

            try {
                int idProduto = Integer.parseInt(id_produto);
                produtoController.deletarProduto(idProduto);

                txtProdutoId.setText(null);
                txtProdutoNome.setText(null);
                txtProdutoQuant.setText(null);
                txtProdutoPreco.setText(null);

                CarregarTabela();   
        
            } catch (Exception e) {
                
                
            }          
        }  
    }//GEN-LAST:event_btnProdutoDeleteActionPerformed

    
    
    private void setarCamposUpdate(){
             // Obtém a linha selecionada
        int linhaSelecionada = tbProduto.getSelectedRow();

        // Verifica se alguma linha está selecionada
        if (linhaSelecionada != -1) {
            // Obtém o modelo de dados da tabela
            TableModel dadosTabela = tbProduto.getModel();

            // Obtém o número de colunas na tabela
            int columnCount = dadosTabela.getColumnCount();

            // Cria um array para armazenar os valores da linha selecionada
            Object[] dadosLinha = new Object[columnCount];
            
         
            
            txtProdutoId.setText(dadosTabela.getValueAt(linhaSelecionada, 0).toString());
            txtProdutoNome.setText( dadosTabela.getValueAt(linhaSelecionada, 1).toString());
            txtProdutoQuant.setText( dadosTabela.getValueAt(linhaSelecionada, 2).toString()); 
            txtProdutoPreco.setText( dadosTabela.getValueAt(linhaSelecionada, 3).toString()); 
            
            //System.out.println("Aqui: ");
            
        }  
    }
    private void tbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutoMouseClicked
       setarCamposUpdate();
    }//GEN-LAST:event_tbProdutoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProdutoAtualizar;
    private javax.swing.JButton btnProdutoCriar;
    private javax.swing.JButton btnProdutoDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProduto;
    private javax.swing.JTextField txtProdutoId;
    private javax.swing.JTextField txtProdutoNome;
    private javax.swing.JTextField txtProdutoPreco;
    private javax.swing.JTextField txtProdutoQuant;
    // End of variables declaration//GEN-END:variables
}
